a=list(range(11))
# print(a)
# print(len(a))
# print(max(a))
# print(min(a))
# print(sum(a))
# a.append(11)
# print(a)
# a.append(12)
# a.insert(1,13)
# print(a)
# a.extend(list(range(13,18,1)))
# a.extend(list(range(20)))
# a.pop()
# a.pop()
# a.pop()
# a.remove(15)
# print(a)
# a.remove(13)
# a.remove(10)
# a.remove(0)
# a.sort()
# a.insert(0,10)
# a.sort()
# a.insert(0,10)
# a.count(10)
# print(a)
# a.insert(0,10)
# print(a.count(10))
# print(a.index(3))
# print(a.sort())
# print(a)
b=a.copy()
print(b)
